name: Scenario-1 
on: [push]

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - name: Chcekout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Maven
        run: |
          mvn clean install
    # - uses: actions/checkout@v4
    # - uses: actions/setup-java@v3
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'
    # - run: mvn --batch-mode --update-snapshots verify
    # - run: mkdir staging && cp target/*.jar staging
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: Package
    #     path: staging

  
